CREATE TABLE IF NOT EXISTS slug_redirects (old_slug TEXT PRIMARY KEY, new_slug TEXT NOT NULL);
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Scaling', 'scaling');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Xerostomia / Dry Mouth', 'xerostomia');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Root Canal', 'root-canal');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('골유착-osseointegration', 'osseointegration');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('건강보험-임플란트', 'implant-insurance');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('치은비대', 'gingival-enlargement');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('치아-구조도', 'tooth-structure');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('리튬디실리케이트', 'emax-lithium-disilicate');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('레진빌드업', 'resin-buildup-procedure');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Facial Swelling 치성', 'facial-swelling');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Tooth Fracture 자각 증상', 'tooth-fracture-symptom');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Abutment', 'abutment');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Peri-implantitis', 'peri-implantitis');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Periodontitis', 'periodontitis');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Pericoronitis', 'pericoronitis');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Xerostomia', 'xerostomia');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Halitosis', 'halitosis');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Fluoride', 'fluoride');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Pulpitis', 'pulpitis');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Zirconia', 'zirconia');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Apicoectomy', 'apicoectomy');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Bisphosphonate', 'bisphosphonate');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Cementum', 'cementum');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Perforation', 'perforation');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Abrasion', 'abrasion');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Bridge', 'bridge');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Enamel', 'enamel');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Gingivitis', 'gingivitis');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Edentulism', 'edentulism');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Suture', 'suture');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Autograft', 'autograft');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Xenograft', 'xenograft');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('HbA1c', 'hba1c');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Gingivectomy', 'gingivectomy');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Edema', 'edema');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Microfracture', 'microfracture');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Nicotine', 'nicotine');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Reendotreatment', 'reendotreatment');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Gingiva', 'gingiva');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Osstem', 'osstem');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Malocclusion', 'malocclusion');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Tooth', 'tooth');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Dentin', 'dentin');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Canine', 'canine');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Maxilla', 'maxilla');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Mandible', 'mandible');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Mesial', 'mesial');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Distal', 'distal');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Eruption', 'eruption');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Midline', 'midline');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Cavity', 'cavity');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Microdontia', 'microdontia');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Macrodontia', 'macrodontia');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Fusion', 'fusion');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Gemination', 'gemination');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Crowding', 'crowding');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Ankylosis', 'ankylosis');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Dilaceration', 'dilaceration');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Hypodontia', 'hypodontia');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Pulpotomy', 'pulpotomy');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Curettage', 'curettage');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Incisor', 'incisor');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Premolar', 'premolar');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Molar', 'molar');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Pontic', 'pontic');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Toothpaste', 'toothpaste');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Bruxism', 'bruxism');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Attrition', 'attrition');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Vestibule', 'vestibule');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Amalgam', 'amalgam');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Periosteum', 'periosteum');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Osteoclast', 'osteoclast');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Osteoblast', 'osteoblast');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Mandibular Torus / Torus Mandibularis', 'mandibular-torus');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Clenching / Bruxism', 'clenching');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Implant Prosthesis', 'implant-prosthesis');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Splint / Occlusal Splint', 'splint');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Occlusal Interference', 'occlusal-interference');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Biologic Width', 'biologic-width');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Food Impaction', 'food-impaction');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Spontaneous Pain', 'spontaneous-pain');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Throbbing Gum Pain', 'throbbing-gum-pain');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Fear of Tooth Fracture / Cracked Tooth Sensation', 'fear-of-tooth-fracture');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Progressive Tooth Shortening', 'progressive-tooth-shortening');
INSERT OR REPLACE INTO slug_redirects (old_slug, new_slug) VALUES ('Dark Line / Marginal Staining', 'dark-line');
